runtime: java17
env: standard
instance_class: F4  # Instance class yang lebih besar

automatic_scaling:
  target_cpu_utilization: 0.65  # Contoh target CPU utilization
  min_instances: 2  # Jumlah minimum instance yang diperbarui
  max_instances: 20  # Jumlah maksimum instance yang diperbarui

entrypoint: java -jar target/treemas-web-api-0.0.1-SNAPSHOT.jar

env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,postgresql"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://google/treemas-cloud?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=treemas-api-405402:asia-southeast2:treemas-db"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "123"

handlers:
- url: /.*
  script: this field is required, but ignored
