runtime: java17
env: standard
instance_class: F2  # Contoh instance class yang lebih besar

automatic_scaling:
  target_cpu_utilization: 0.65  # Contoh target CPU utilization
  min_instances: 1  # Jumlah minimum instance
  max_instances: 10  # Jumlah maksimum instance

entrypoint: java -jar target/treemas-web-api-0.0.1-SNAPSHOT.jar

env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,postgresql"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://google/treemas-cloud?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=treemas-api-403500:asia-southeast1:treemas-db"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "123"

handlers:
- url: /.*
  script: this field is required, but ignored
