server:
  port: 8081
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/treemas_ori
        username: postgres
        password: 123
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    servlet:
        multipart:
            enabled: true
    http:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB