server:
  port: 8081
  tomcat:
    max-swallow-size: 50MB
spring:
  datasource:
    url: jdbc:postgresql://google/treemas-cloud?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=treemas-api-405402:asia-southeast2:treemas-db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
cloud:
  gcp:
    credentials:
      location: C:\Users\Heru M\Desktop\Project\cloud-web-android\Backend\src\main\resources\treemas-api-405402-57ec0885e2ee.json
