server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://google/treemas-cloud?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=treemas-api-403500:asia-southeast1:treemas-db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
servlet:
  multipart:
    enabled: true
http:
  multipart:
    max-file-size: 10MB
    max-request-size: 
cloud:
  gcp:
    credentials:
      location: C:\Users\Heru M\Desktop\Project\Backend-test-feature-andro\src\main\resources\treemas-api-403500-1df5bb95743b.json