server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kontol
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
        hibernate:
            ddl-auto: validate
            format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE